#########################
# project configuration #
#########################

# C++ project
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - libpython3-dev
    - libtbb-dev

install:
  # create deps dir if not existing
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - python3-config --cflags --ldflags
  - cd ..

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - (cd rts/game_MC && make gen && make)
  - (cd rts/game_CF && make gen && make)
  - (cd rts/game_TD && make gen && make)
  - cd rts/backend
  - make clean && make GAME_DIR=../game_MC
  - make clean && make GAME_DIR=../game_CF
  - make clean && make GAME_DIR=../game_TD

