#########################
# project configuration #
#########################

cache:
  apt: true
  directories:
    - $HOME/deps

# C++ project
language: cpp
python:
  - 3.6
  - 3.7
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - libpython3-dev
    - libtbb-dev
install:
  # create deps dir if not existing
  - DEPS_DIR=${HOME}/deps
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - python3-config --cflags --ldflags
  - |
    CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd -

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - (mkdir rts/build_MC && cd rts/build_MC && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python -DGAME_DIR=../game_MC && make)
  - (mkdir rts/build_CF && cd rts/build_CF && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python -DGAME_DIR=../game_CF && make)
  - (mkdir rts/build_TD && cd rts/build_TD && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python -DGAME_DIR=../game_TD && make)
  - (mkdir rts/build_MC && cd rts/build_MC && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python3 -DGAME_DIR=../game_MC && make)
  - (mkdir rts/build_CF && cd rts/build_CF && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python3 -DGAME_DIR=../game_CF && make)
  - (mkdir rts/build_TD && cd rts/build_TD && cmake .. -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python3 -DGAME_DIR=../game_TD && make)
  - (mkdir rts/build_MC && cd rts/build_MC && cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python -DGAME_DIR=../game_MC && make)
  - (mkdir rts/build_CF && cd rts/build_CF && cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python -DGAME_DIR=../game_CF && make)
  - (mkdir rts/build_TD && cd rts/build_TD && cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python -DGAME_DIR=../game_TD && make)